version: '3.6'
services:
    nodeos:
        build: 
            context: .
            args:
                - NODEOS_REPOSITORY=${NODEOS_REPOSITORY}
                - NODEOS_VERSION=${NODEOS_VERSION}
        env_file:
            - .env
        ports:
            - 8888:8888
        tmpfs:
            - /ramdisk:defaults,nosuid,nodev,noatime,nodiratime,exec,size=64G
        volumes:
            - ./shared:/eosio/shared
