version: '3.6'
services:
    nodeos:
        env_file:
            - .env
        extends:
            file: ./configs/docker/nodeos-minimal-api.yaml
            service: nodeos
    nginx:
        depends_on:
            - nodeos
        extends:
            file: ./configs/docker/nginx.yaml
            service: nginx
        profiles: ["nginx"]
