version: '3.6'
services:
    nginx:
        env_file:
            - ../../.env
        image: nginx:latest
        ports:
            - "${NETWORK_PORT_API}:8888"
            - "${NETWORK_PORT_P2P}:9876"
        volumes:
            - ../nginx.conf:/etc/nginx/nginx.conf:ro
            - ../../shared:/eosio/shared